"""
Governed-answer document export (backlog 66).

Renders an already-governed answer to a downloadable DOCX or PDF. This is a
DETERMINISTIC transform of text the Will already approved and the audit record
already holds: no model call, no new content. It is the same shape as TTS,
which renders a governed answer to audio. Nothing here belongs to a faculty or
the TCB, and the load-bearing rule (CLAUDE.md invariant, and the vision item
32z) is respected because formatting invents nothing that the Conscience did
not score.

Two formats:
- DOCX: a focused markdown -> python-docx builder covering what agents emit
  (headings, paragraphs, bold/italic/inline-code, bullet/numbered lists, code
  blocks, blockquotes, tables, rules, links).
- PDF: markdown -> HTML (the `markdown` lib) -> PDF (`xhtml2pdf`), both pure
  Python so the image needs no system libraries.
"""
from __future__ import annotations

import io
import re
from typing import Optional, Tuple

# Guardrail: a document is a render of one answer, not a batch job. Well above
# any real answer; only bounds abuse.
MAX_EXPORT_CHARS = 500_000

# What every exported document carries, for transparency once it leaves the
# governed environment. Kept plain and factual per the writing-style rule.
_FOOTER_PREFIX = "Generated by "
_FOOTER_SUFFIX = " and exported from SAFi. AI-generated content; verify before relying on it."


def _footer_text(attribution: Optional[str]) -> str:
    who = (attribution or "an AI agent").strip() or "an AI agent"
    return f"{_FOOTER_PREFIX}{who}{_FOOTER_SUFFIX}"


# --- inline markdown -> styled runs ------------------------------------------

# Order matters: code first (its content is literal), then bold, then italic.
_INLINE_RE = re.compile(
    r"(?P<code>`[^`]+`)"
    r"|(?P<bold>\*\*[^*]+\*\*|__[^_]+__)"
    r"|(?P<italic>\*[^*]+\*|_[^_]+_)"
)
_LINK_RE = re.compile(r"!?\[([^\]]*)\]\(([^)]+)\)")


def _delink(text: str) -> str:
    """[label](url) -> 'label (url)'; ![alt](url) -> 'alt'. python-docx has no
    easy hyperlink, and a document that silently drops URLs is worse than one
    that shows them in parentheses."""
    def repl(m):
        label, url = m.group(1), m.group(2)
        if m.group(0).startswith("!"):
            return label  # image: keep alt text only
        if not label:
            return url
        return label if label == url else f"{label} ({url})"
    return _LINK_RE.sub(repl, text)


def _add_inline(paragraph, text: str) -> None:
    text = _delink(text)
    pos = 0
    for m in _INLINE_RE.finditer(text):
        if m.start() > pos:
            paragraph.add_run(text[pos:m.start()])
        if m.group("code"):
            run = paragraph.add_run(m.group("code")[1:-1])
            run.font.name = "Consolas"
        elif m.group("bold"):
            run = paragraph.add_run(m.group("bold")[2:-2])
            run.bold = True
        elif m.group("italic"):
            run = paragraph.add_run(m.group("italic")[1:-1])
            run.italic = True
        pos = m.end()
    if pos < len(text):
        paragraph.add_run(text[pos:])


_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*)$")
_BULLET_RE = re.compile(r"^\s*[-*+]\s+(.*)$")
_NUMBERED_RE = re.compile(r"^\s*\d+[.)]\s+(.*)$")
_HR_RE = re.compile(r"^\s*([-*_])\1{2,}\s*$")
_FENCE_RE = re.compile(r"^\s*```")
_TABLE_SEP_RE = re.compile(r"^\s*\|?\s*:?-{2,}.*\|.*$")


def _split_row(line: str) -> list:
    line = line.strip()
    if line.startswith("|"):
        line = line[1:]
    if line.endswith("|"):
        line = line[:-1]
    return [c.strip() for c in line.split("|")]


def _md_to_docx(text: str, title: str, attribution: Optional[str]) -> bytes:
    from docx import Document
    from docx.shared import Pt, RGBColor

    doc = Document()
    if title:
        doc.add_heading(title, level=0)

    lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    i = 0
    n = len(lines)
    while i < n:
        line = lines[i]

        # Fenced code block
        if _FENCE_RE.match(line):
            i += 1
            code_lines = []
            while i < n and not _FENCE_RE.match(lines[i]):
                code_lines.append(lines[i])
                i += 1
            i += 1  # closing fence
            p = doc.add_paragraph()
            run = p.add_run("\n".join(code_lines))
            run.font.name = "Consolas"
            run.font.size = Pt(9)
            continue

        # Table: a pipe row followed by a separator row
        if "|" in line and i + 1 < n and _TABLE_SEP_RE.match(lines[i + 1]):
            header = _split_row(line)
            i += 2  # header + separator
            rows = []
            while i < n and "|" in lines[i] and lines[i].strip():
                rows.append(_split_row(lines[i]))
                i += 1
            table = doc.add_table(rows=1, cols=len(header))
            try:
                table.style = "Light Grid Accent 1"
            except KeyError:
                pass
            for j, cell_text in enumerate(header):
                cell = table.rows[0].cells[j]
                cell.paragraphs[0].clear()
                run = cell.paragraphs[0].add_run(cell_text)
                run.bold = True
            for r in rows:
                cells = table.add_row().cells
                for j in range(len(header)):
                    val = r[j] if j < len(r) else ""
                    cells[j].paragraphs[0].clear()
                    _add_inline(cells[j].paragraphs[0], val)
            continue

        stripped = line.strip()
        if not stripped:
            i += 1
            continue

        if _HR_RE.match(line):
            i += 1
            continue

        m = _HEADING_RE.match(line)
        if m:
            level = min(len(m.group(1)), 6)
            doc.add_heading(m.group(2).strip(), level=level)
            i += 1
            continue

        if line.lstrip().startswith(">"):
            quote = line.lstrip()[1:].strip()
            p = doc.add_paragraph(style="Intense Quote" if _has_style(doc, "Intense Quote") else None)
            _add_inline(p, quote)
            i += 1
            continue

        m = _BULLET_RE.match(line)
        if m:
            p = doc.add_paragraph(style="List Bullet")
            _add_inline(p, m.group(1))
            i += 1
            continue

        m = _NUMBERED_RE.match(line)
        if m:
            p = doc.add_paragraph(style="List Number")
            _add_inline(p, m.group(1))
            i += 1
            continue

        # Plain paragraph
        p = doc.add_paragraph()
        _add_inline(p, stripped)
        i += 1

    # Transparency footer
    doc.add_paragraph()
    foot = doc.add_paragraph()
    frun = foot.add_run(_footer_text(attribution))
    frun.italic = True
    frun.font.size = Pt(8)
    frun.font.color.rgb = RGBColor(0x8A, 0x8A, 0x8A)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _has_style(doc, name: str) -> bool:
    try:
        _ = doc.styles[name]
        return True
    except KeyError:
        return False


# --- markdown -> HTML -> PDF ---------------------------------------------------

_PDF_CSS = """
@page { size: letter; margin: 2.2cm 2cm; }
body { font-family: Helvetica, Arial, sans-serif; font-size: 11pt; color: #1a1a1a; line-height: 1.45; }
h1 { font-size: 20pt; margin: 0 0 12pt 0; }
h2 { font-size: 15pt; margin: 16pt 0 6pt 0; }
h3 { font-size: 13pt; margin: 14pt 0 5pt 0; }
h4, h5, h6 { font-size: 11pt; margin: 12pt 0 4pt 0; }
p { margin: 0 0 8pt 0; }
ul, ol { margin: 0 0 8pt 18pt; }
li { margin: 0 0 3pt 0; }
code { font-family: Courier, monospace; font-size: 10pt; background: #f2f2f2; }
pre { font-family: Courier, monospace; font-size: 9.5pt; background: #f5f5f5; padding: 8pt; }
blockquote { margin: 0 0 8pt 0; padding: 4pt 10pt; color: #555; border-left: 3pt solid #cccccc; }
table { border-collapse: collapse; width: 100%; margin: 0 0 10pt 0; }
th, td { border: 0.5pt solid #999999; padding: 4pt 6pt; font-size: 10pt; text-align: left; }
th { background: #eeeeee; }
.doc-title { font-size: 22pt; font-weight: bold; margin: 0 0 16pt 0; }
.doc-footer { margin-top: 20pt; padding-top: 8pt; border-top: 0.5pt solid #cccccc;
              font-size: 8pt; font-style: italic; color: #8a8a8a; }
"""


def _md_to_pdf(text: str, title: str, attribution: Optional[str]) -> bytes:
    import html as _html
    import markdown as _markdown
    from xhtml2pdf import pisa

    body = _markdown.markdown(
        text,
        extensions=["extra", "sane_lists", "nl2br"],
        output_format="html5",
    )
    title_html = f'<div class="doc-title">{_html.escape(title)}</div>' if title else ""
    footer_html = f'<div class="doc-footer">{_html.escape(_footer_text(attribution))}</div>'
    doc = (
        f"<!DOCTYPE html><html><head><meta charset='utf-8'>"
        f"<style>{_PDF_CSS}</style></head><body>"
        f"{title_html}{body}{footer_html}"
        f"</body></html>"
    )
    out = io.BytesIO()
    result = pisa.CreatePDF(src=doc, dest=out, encoding="utf-8")
    if result.err:
        raise RuntimeError("PDF rendering failed")
    return out.getvalue()


# --- public entry point -------------------------------------------------------

def render(text: str, title: str, fmt: str,
           attribution: Optional[str] = None) -> Tuple[bytes, str, str]:
    """Render governed answer text to a document.

    Returns (bytes, mimetype, extension). Raises ValueError for a bad format or
    empty/oversized text.
    """
    if not text or not text.strip():
        raise ValueError("Nothing to export.")
    if len(text) > MAX_EXPORT_CHARS:
        raise ValueError("Answer is too long to export.")
    fmt = (fmt or "").lower()
    title = (title or "").strip()

    if fmt == "docx":
        return (
            _md_to_docx(text, title, attribution),
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "docx",
        )
    if fmt == "pdf":
        return (_md_to_pdf(text, title, attribution), "application/pdf", "pdf")
    if fmt in ("md", "markdown"):
        # The faithful source: the answer's own markdown, with the same
        # transparency footer appended as a plain markdown block. No render.
        body = text if text.endswith("\n") else text + "\n"
        out = f"{body}\n---\n\n_{_footer_text(attribution)}_\n"
        return (out.encode("utf-8"), "text/markdown", "md")
    raise ValueError(f"Unsupported format '{fmt}'.")
